$schema: http://json-schema.org/draft-04/hyper-schema
title: Local config
type: object
properties:
  slack:
    type: object
    required:
      - hooks
    properties:
      hooks:
        type: array
        items:
          type: string
          format: url
