package:
  version: 1.4.8
  url: https://github.com/pooza/ginseng-core
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
  description: ginseng core libraries
  license: MIT
cert:
  url: https://curl.haxx.se/ca/cacert.pem
error:
  backtrace:
    level: 5
youtube:
  urls:
    videos: https://www.googleapis.com/youtube/v3/videos
mastodon:
  url: https://mstdn.b-shock.org/
  token: test
  test_toot: 0
